Openredu/Openredu

app/models/access_token.rb
app/models/licensed_invoice.rb
app/models/oauth2_token.rb
app/models/package_invoice.rb
app/models/user_course_association.rb
app/models/user_course_invitation.rb

Correção de sintaxe em modelos que causava erros ao tentar criar uma
nova instância do banco de dados.

Correção de sintaxe em modelos

---

.gitignore
db/schema.rb

Esta modificação possibilita #40.

Remove db/schema.rb do gitignore

---

.travis.yml
Gemfile
Gemfile.lock
config/database.travis.yml

Configura integração contínua com Travis

---

Gemfile
Gemfile.lock

Bônus:
- Usa https para source rubygems
Closes #46

Remove sources desnecessários do Gemfile

---

Gemfile.lock
app/views/lectures/admin/_choose_type.html.erb
app/views/lectures/admin/_seminar_fields.html.erb
config/initializers/abstract_mysql2_adapter.rb

https://github.com/Openredu/Openredu/issues/55

Remove radio video

---

Gemfile.lock
app/views/lectures/show_exercise.html.erb
app/views/questions/show.html.erb
app/views/results/admin/edit.html.erb
app/views/results/admin/index.html.erb
app/views/subjects/_sidebar_without_comment.html.erb
config/initializers/abstract_mysql2_adapter.rb

https://github.com/Openredu/Openredu/issues/58

Remove comment button

---

lib/assets/javascripts/boring-browser/outdated-browser.js

https://openredu.atlassian.net/browse/DEV-152https://openredu.atlassian.net/browse/DEV-152

Remove condicional do flash

---

app/views/folders/_admin.html.erb
app/views/folders/_index.js.erb

https://github.com/Openredu/Openredu/issues/107

Resolve 107

---

app/views/quotas/_quotas_old.html.erb

Resolve a issue https://github.com/Openredu/Openredu/issues/110

Resolve 110

---

README.markdown

Atualização de links que faziam referência ao redu, para links que fazem referência ao openRedu.
Colocando link para setup atualizado para ubuntu e link depracated para as outras plataformas.
Removendo setup e outras configurações que não fazem mais sentido para o openRedu.

Atualização do readme

---

.gitignore

Corrige .gitignore

---

db/migrate/20170713201420_remove_ipaper_id_and_ipaper_access_key_from_documents.rb
db/schema.rb

Corrige erro na migration de remoção do ipaper

---

.travis.yml
script/grant_travis_privileges_on_mysql.sh

Cria script de configuração do mysql para o travis

---

app/views/shared/_analytics.html.erb

Credenciais do ambiente de produção (openredu.ufpe.br)
resolve #150

Configura credenciais do google analytics

---

app/helpers/lectures_helper.rb
app/models/seminar.rb
spec/models/seminar_spec.rb

@rafaellsma esquecesse o PR, vou fazer o merge!

Add https to external video url

---

app/assets/javascripts/application.js
app/views/lectures/_document.html.erb

Configura CDN para o pdfJS

---

app/assets/javascripts/chat.jquery.js
app/controllers/chats_controller.rb
app/views/presence/_chat_window.html.erb
spec/controllers/chats_controller_spec.rb

Chat do openredu realtime utilizando o serviço faye e reutilizando o antigo frontend.
https://github.com/Openredu/faye-openrendu

Chat do Openredu

---

spec/requests/api/vis_spec.rb

Segui a recomendação do Rspec e atualizei o Authorization dentro dos headers

Atualiza o Authorization nos headers

---

app/models/audience.rb

Adiciona validação de nome no model de Audience

---

README.markdown
script/setup/init
script/setup/run

Closes #22
Copiado de https://gist.github.com/JoaoGFarias/b00c8a527599cbdfb5c9
Co-authored-by: João Farias <joao@thatsabug.com>

Adiciona scripts pra setup no Mac

---

app/models/user.rb
app/views/users/_form.html.erb

Atualiza campo Celular para 9 dígitos

---

app/controllers/api/subjects_controller.rb
app/representers/api/subject_representer.rb

Retorna porcentagem concluída da lecture pelo usuário via API

---

CHANGELOG.md
bin/release-contrib.rb

https://github.com/Openredu/Openredu/blob/changelog/CHANGELOG.md

Adiciona CHANGELOG.md
